# -*- coding: utf-8 -*-
"""Kümeleme.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KLS9bjHSlONO5OZpsi9eItU7XiLTLef
"""

# 'contextily' kütüphanesi eksik olduğu için yükleniyor.
!pip install contextily

import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
import matplotlib.pyplot as plt
import numpy as np
import contextily as ctx
from math import radians, sin, cos, sqrt, atan2  # haversine için

# ────────────────────────────────────────────────
# Özel metrik: Konum (haversine km) + Zaman (gün farkı)
# ────────────────────────────────────────────────
def custom_metric(p1, p2):
    # p: [enlem, boylam, zaman_gun]
    R = 6371.0  # Dünya yarıçapı km
    lat1, lon1 = radians(p1[0]), radians(p1[1])
    lat2, lon2 = radians(p2[0]), radians(p2[1])

    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    dist_km = R * c

    zaman_fark_gun = abs(p1[2] - p2[2])

    # Ağırlık: konum km + zaman gün
    return dist_km + zaman_fark_gun * 5.0

# ────────────────────────────────────────────────
# 1. Veri yükleme ve hazırlama
# ────────────────────────────────────────────────
df = pd.read_csv("YSA2.csv", sep=";", encoding="ISO-8859-9")
df.columns = df.columns.str.strip()

# Koordinat düzeltme
if df['Enlem'].max() > 90 or df['Boylam'].max() > 180:
    df['Enlem'] /= 10.0
    df['Boylam'] /= 10.0

# Tarih oluşturma
df['datetime'] = pd.to_datetime(df['Olus tarihi'] + ' ' + df['Olus zamani'], dayfirst=True)
df = df.dropna(subset=['datetime'])
df = df.sort_values('datetime').reset_index(drop=True)

# Zamanın normalize etme (gün cinsine)
df['Zaman_Gun'] = (df['datetime'] - df['datetime'].min()).dt.total_seconds() / 86400.0

# GeoDataFrame (arkaplan haritası)
geometry = [Point(xy) for xy in zip(df['Boylam'], df['Enlem'])]
gdf = gpd.GeoDataFrame(df, geometry=geometry, crs="EPSG:4326")

# Opsiyonel filtre (düşük M'leri çıkar)
gdf = gdf[gdf['xM'] > 3.0].copy()

# Özellik matrisi: [Enlem, Boylam, Zaman_Gun]
X = gdf[['Enlem', 'Boylam', 'Zaman_Gun']].values

# Standartlaştır
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# ────────────────────────────────────────────────
# 2. DBSCAN ile Kümeleme (zaman + konum)
# ────────────────────────────────────────────────
eps_total = 15.0  # maks toplam "mesafe" (km + ağırlıklı gün)
min_samples = 15   # min deprem/küme

db = DBSCAN(
    eps=eps_total,
    min_samples=min_samples,
    metric=custom_metric
)

gdf['kume'] = db.fit_predict(X)  # X_scaled yerine X kullandık ??

# Sonuç özeti
n_clusters = len(set(gdf['kume'])) - (1 if -1 in gdf['kume'] else 0)
n_noise = list(gdf['kume']).count(-1)
print(f"Toplam küme sayısı: {n_clusters}")
print(f"Gürültü noktalar: {n_noise}")
print(gdf['kume'].value_counts())

# ────────────────────────────────────────────────
# 3. Harita Görselleştirme
# ────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(14, 10))

gdf.plot(
    ax=ax,
    column='kume',
    categorical=True,
    cmap='tab20',
    markersize=10,
    alpha=0.7,
    legend=True,
    missing_kwds={"color": "lightgray", "label": "Gürültü"}
)

# Küme merkezleri
for cluster_id in gdf['kume'].unique():
    if cluster_id == -1: continue
    cluster = gdf[gdf['kume'] == cluster_id]
    center = cluster.geometry.unary_union.centroid
    ax.plot(center.x, center.y, 'ko', markersize=12, zorder=10)
    ax.text(center.x + 0.02, center.y, f'{cluster_id}', fontsize=10, weight='bold')

ax.set_title(f'Marmara Deprem Kümeleri (Zaman + Konum)\n(DBSCAN – eps \u2248 {eps_total} [km + gün*3], min {min_samples} deprem)', fontsize=14)
ctx.add_basemap(ax, crs=gdf.crs.to_string(), source=ctx.providers.CartoDB.Positron)
plt.xlabel('Boylam')
plt.ylabel('Enlem')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()